package com.mercadolibre.android.andesui.switch.status

internal interface AndesSwitchStatusInterface
internal object AndesSwitchStatusChecked : AndesSwitchStatusInterface
internal object AndesSwitchStatusUnchecked : AndesSwitchStatusInterface
