package com.mercadolibre.android.andesui.switchandes.status

internal interface AndesSwitchStatusInterface
internal object AndesSwitchStatusChecked : AndesSwitchStatusInterface
internal object AndesSwitchStatusUnchecked : AndesSwitchStatusInterface
