package com.mercadolibre.android.andesui.switchandes.type

internal interface AndesSwitchTypeInterface
internal object AndesSwitchTypeEnabled : AndesSwitchTypeInterface
internal object AndesSwitchTypeDisabled : AndesSwitchTypeInterface
