name: 'Create and/or Update edited issues to project'

on:
  issues:
    types:
      [opened]

jobs:
  create-update-project:
    name: Create/update project issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/add-to-project@v0.3.0 # This adds the issue to the project
        with:
          project-url: https://github.com/orgs/mercadolibre/projects/252
          github-token: ${{ secrets.GH_PROJECT_TK }}
        id: add-project
      - uses: titoportas/update-project-fields@v0.1.0
        with:
          project-url: https://github.com/orgs/mercadolibre/projects/252
          github-token: ${{ secrets.GH_PROJECT_TK }}
          item-id: ${{ steps.add-project.outputs.itemId }}
          field-keys: Squad,Status
          field-values: Andes,🔵 TODO