name: 'Mark Issue as DONE when closed'

on:
  issues:
    types:
      - closed

jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get projectV2 item-id for issue
        uses: ./.github/actions/get-project-item/
        with:
          issue-number: ${{ github.event.issue.number }}
          repository-owner: ${{ github.repository_owner }}
          repository-name: ${{ github.event.repository.name }}
          github-token: ${{ secrets.GH_PROJECT_TK }}
        id: get-item-id
      - name: Get current date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        id: date
      - name: Update item
        uses: titoportas/update-project-fields@v0.1.0
        with:
          project-url: https://github.com/orgs/mercadolibre/projects/252
          github-token: ${{ secrets.GH_PROJECT_TK }}
          item-id: ${{ steps.get-item-id.outputs.item-id }}
          field-keys: Status,FinishedAt
          field-values: ✅ DONE,${{ steps.date.outputs.date }}