name: '[Optional] Link PR to Issue and project item'

on:
  pull_request:
    types: [opened]

jobs:
  issue-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tkt-actions/add-issue-links@v1.8.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          branch-prefix: '(?:fix\/|feature\/)[^0-9]*'
          resolve: true
      - name: Get issue number
        uses: ./.github/actions/get-issue/
        with:
          branch-name: ${{ github.event.pull_request.head.ref }}
        id: get_issue
      - name: Get projectV2 item-id for issue
        if: ${{ steps.get_issue.outputs.issue-number != -1 }}
        uses: ./.github/actions/get-project-item/
        with:
          issue-number: ${{ steps.get_issue.outputs.issue-number }}
          repository-owner: ${{ github.repository_owner }}
          repository-name: ${{ github.event.repository.name }}
          github-token: ${{ secrets.GH_PROJECT_TK }}
        id: get-item-id
      - name: Update item
        if: ${{ steps.get_issue.outputs.issue-number != -1 }}
        uses: titoportas/update-project-fields@v0.1.0
        with:
          project-url: https://github.com/users/titoportas/projects/3
          github-token: ${{ secrets.GH_PROJECT_TK }}
          item-id: ${{ steps.get-item-id.outputs.item-id }} # Use the item-id output of the previous step
          field-keys: Status
          field-values: 👀 IN REVIEW
